### ISSUE TITLE
CIP 0037 - Unambiguous name for ERC-20 on Celo chain - Discussions

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/celo-proposals#181]
Discussions for [CIP-37](https://github.com/celo-org/celo-proposals/blob/master/CIPs/cip-0037.md)

**Comment by zviadm** [comment]
Copying comments here from the original PR:

* Big +1 to this effort.
* Overall, would support any name that we agree on and that we can all use consistently through out all the apps/docs/etc. I.e. having a name is more important than the name itself to me.
* If we are voting for a name, my personal preference would be to choose a name that doesn't sound like ERC-20 at all:
-- Something like, Celo Standard Token (CST), or Celo Fungible Token (CFT). Name with no `-20` in it.
-- My least favorite option is cERC-20, which I think is still too confusing and users can easily assume that ERC-20 and cERC-20 are interchangeable, especially because Eth/Celo addresses have the same format.

**Comment by aaronmgdr** [comment]
Background on this is that I was browsing discord and saw both people saying stuff like CELO isnt an ERC-20 token, and in other channels that it is. which in context are both correct, yet ultimately confusing. The key thing is that there is standard ERC-20, which describes an interface for implementing tokens on various blockchains. and then a common usage which I would say has taken on a meaning more like "crypto token coin I can use in various wallets / DEXes", with an implication that it is on Ethereum. 

So for core devs its likely we will continue talking about ERC-20 interfaces, but for people building wallets having a way to communicate support of cUSD, cEUR, tBTC, (UBESwap token?) etc etc etc. that live on celo and follow the interface without having to deal with many support tickets for people sending GRT or DAI, because the  wallet "supported ERC-20" will help build trust in the Celo ecosystem.

**Comment by aaronmgdr** [comment]
_copying over from original PR_

yes very much not set on any particular name.

like @zviadm suggested I also was thinking abut Celo Standard Token or Celo Token Standard but could see it getting confused with CELO native token.

I think the benefit of 20 is mostly because the implementations of the standard on other chains have it in their name and it seems like a nice convention to stick with. but Its by no means required in my opinion.

Im a fan of `CFT`

**Comment by willkraft** [comment]
Somebody on the last developer call mentioned a near-term fix for this issue is to update the documentation to make it clear that ERC-20-conforming tokens on the Celo blockchain are not compatible with the Ethereum blockchain, so I made this [doc with potential updates](https://docs.google.com/document/d/1XHPT-ljWuJG5559Z3UJ9hV5jaaBtCLS2_5r29Q9QNZs/edit#) to 7 places in the documentation where this could be most helpful

Feel free to add comments, and if those changes look good, I'll update the docs

**Comment by aaronmgdr** [comment]
@willkraft  nice work.  @barbaraliau might be better than myself for reviewing that doc

**Comment by willkraft** [comment]
Thanks, @barbaraliau let me know what you think of those changes, and I can update the docs if they look okay

**Comment by willkraft** [comment]
Hi @barbaraliau, hope you've had a good weekend! I wanted to follow up here - let me know what you think about those changes to the docs, and I can submit them if they look okay

**Comment by zviadm** [comment]
How should we proceed with this? We are adding more and more tools and documentation that needs to reference ERC20 like tokens on Celo. Imo, sooner we have the name the better. 

I would propose we just do a poll among stakeholders, and just choose a name and go with it. Having a name seems strictly better than waiting for a perfect option.

**Comment by aaronmgdr** [comment]
For my part i've let it go as i'm outside of my area of expertise and there seemed to be some strong opposition from some because it technically is the erc20 interface and I worried at this point it's to late.   I do think CFT is a great consumer name. 

If this does happen i think i will need to be by app developers coming together.

**Comment by patricknbaron** [comment]
I like CRC-20 because it is close enough to ERC-20 that it intuitively infers what it is, but is different enough to indicate that it's not an Ethereum based token.

**Comment by YazzyYaz** [comment]
Relevant tweet on naming conventions https://twitter.com/brendan_dharma/status/1392243927076392962

Also having @prestwich in the conversation is good. There's this proposal by Pedro Gomez https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-10.md
