### ISSUE TITLE
Celo Governance Call 5: Governance Working Group

### ISSUE THREAD

**Issue by YazzyYaz** [celo-org/celo-proposals#197]
# Celo Governance Call 5: Governance Working Group

![governance-call-end-cards (2)](https://user-images.githubusercontent.com/9094204/111877547-3c8fbb00-897a-11eb-8aab-97123a774428.jpg)

When: March 25th, 2021. 1 PM EST / 10 AM PST 60 minutes max
Where: Celo Zoom [Event](https://zoom.us/j/92524002804) (Instructions on joining found in the calendar event below)
Zoom Passcode: 949247
Calendar Event: Add to your calendar [here](https://calendar.google.com/event?action=TEMPLATE&tmeid=NnZlMHJoNzJuaDUwcGVpZDBkZ3JjZXFia28gY185c3U2aWNoMXVobWV0cjRvYjNzaWo2a2Fxc0Bn&tmsrc=c_9su6ich1uhmetr4ob3sij6kaqs%40group.calendar.google.com)

**Note: This is a special governance call for creating a working group around improving the governance process.**

### Tensions
* Governance and CGP process not as specified as CIP Process. See Cosmo's [example](https://github.com/cosmos/governance).
* Need to resolve inconsistency between proposalID and CGP Numbers.
* CGPs with missing sections or underspecified.
* Need more CGP editors.
* CGP governable parameters need to be tracked down in the CIP process.
* Coordination with approvers needs a more specified Verification process.
    * Provide timely push notifications to approvers (when proposals are posted and as expiry approaches), to give them time to review 
* `celocli governance:view` is difficult to understand and fails to helpfully parse some proposals.
* Document the proposal code verification procedure. Make sure many non-cLabbers know of it and have successfully invoked it. (Sufficiently many to really catch problems, if they arise.)
* Never post proposals until they are fully specified, including code verification procedures.
* Try to make CGP text reasonably stand-alone, giving the gist even to readers who don't follow the links. (But do provide the links for further context and community discussion.)
* Proactively seek community input on proposals before they're posted. In particular, seek non-cLabs input on proposals that involve privileges to cLabs or cLabbers.
* Ensure Audit Reports are publicized prior to submission.
* Move governance to its own repository outside the current repo to separate CIP and CGP processes.

### Solutions
* Ideas by @aslawson this [doc](https://docs.google.com/document/d/1_aLO9xnO6ho02BuFGTReuNsDWMEhDS4Omsc48CiN4O8/edit)

_Please post all relevant proposals below that should be discussed and evaluated_

**Comment by YazzyYaz** [comment]
https://docs.google.com/document/d/1ZuYdwh4ZFtiEvXaE7Ow6NhKjBvLwjn-M_-ryDBuPZLM/edit#

**Comment by Pinotio** [comment]
Thanks @YazzyYaz for hosting. Just some follow up remarks:

**1. Definition of Community for Governance Matters**
In discussing governance, I see the importance of defining a North Star and target audience.

As I understand, the goal of Valora App (and much of the Celo platform?) is to enable people (often those without financial access) to use cUSD (or cEUR etc.) for transactions. The existence of Celo tokens is (or will be) incidental to many end users. They don't need (or want?) to know that crypto is enabling the Valora payment platform (or other Celo platform solutions that provide them access to financial tools).

Now the question of whether - for governance matters - "Community" means Celo owners or cUSD users? Under the current system, since only Celo tokens can vote, only Celo owners are enfranchised (empowered _through_ governance). What can be done for broader community members is 1) allow them to be informed of a transparent governance process, 2) allow them to submit proposals to governance (already the case but complicated).

Under the current voting arrangements, one "North Star" (that is compatible with voting arrangements) might be the following:
"For governance to enfranchise Celo owners through a process that is transparent and keeps the Celo community (broadly defined to include cUSD, cEUR owners, app developers etc.) informed". [It's an example, don't take it too seriously...]

To this effect, github-style communication is perhaps best for Celo owners and medium-style communication best for the broader community.

**2. Diversifying the Franchise**
Strong governance requires participation/control _and_ a clear process. Today's call was focused on achieving a clearer process.

Just as there is discussion around "clear process", I believe there needs to be just as much discussion around "participation/control" (specifically wrt voting)

Currently, control is focused right now with a small group of validators.

Now, the question of which should come first: A strong voting process OR a diversification of control?

I believe that both need to happen together because with new people holding control, there will naturally be new information from new participants informing process design.

For this reason, I suggest that meetings to discuss how validator control can be diversified are just as important as meetings to discuss the process through which Celo owners vote.

**Comment by willkraft** [comment]
Hey all, here are key takeaways from today's governance call: [Celo Governance Call #5_2021.03.25.pdf](https://github.com/celo-org/celo-proposals/files/6209191/Celo.Governance.Call.5_2021.03.25.pdf)

**Comment by YazzyYaz** [comment]
Thanks @willkraft!

**Comment by YazzyYaz** [comment]
Video of the call https://www.youtube.com/watch?v=ZT-L--xhiU0

**Comment by YazzyYaz** [comment]
New call scheduled https://github.com/celo-org/celo-proposals/issues/201
